<?php
$z[0]=Array("litpic","",486,501);
$z[0][4]=array();
$z[1]=Array("title","",508,548);
$z[1][4]=array();
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("arcurl","",865,881);
$z[2][4]=array();
$z[3]=Array("arcurl","",1010,1026);
$z[3][4]=array();
$z[4]=Array("title","",1569,1584);
$z[4][4]=array();
$z[5]=Array("arcurl","",1956,1972);
$z[5][4]=array();
$z[6]=Array("arcurl","",2085,2101);
$z[6][4]=array();

?>