<!--<li class="case-li am-u-sm-6 am-u-md-6 am-u-lg-3">
										<div class="am-gallery-item case-img1">
											<a href="[field:arcurl /]">
												<img src="[field:litpic/]" alt="[field:title function='html2text(@me)'/]" />
											</a>
										</div>
										<div class="case-li-mengban">
											<div class=" case-word">
												<h3 class="am-gallery-title">[field:title /]</h3>
												<p>[field:pubdate function="MyDate('Y-m-d',@me)" /]</p>
												<a href="[field:arcurl /]" ><span><i class="am-icon-eye"></i>查看更多</span></a>
											</div>
										</div>
									</li>-->
									
									<div class="item inline-block absolute wow fadeInUp" cid="0" status="on">
                                    <div class="main trans">
                                        <div class="cover scale relative">
                                            <img src="{dede:global.cfg_templets_skin/}/picture/notebook.png" class="trans scale-img max-w100">
                                            <div class="img absolute text-center fz0">
                                                <img src="[field:litpic/]" alt="[field:title function='html2text(@me)'/]" class="trans scale-img">
                                            </div>
                                            <div class="opt absolute trans hide768">
                                                <div class="button-bg border-box clean">
                                                    <a href="#"​ class="button fl trans text-center" rel="nofollow">预览</a>
                                                    <a href="#"​ class="links fr trans">
                                                        <i></i>详细
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="info clean">
                                            <div class="left fl">
                                                <div class="name"> [field:title /]</div>
                                                <div class="category"></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="mask trans"></div>
                                    <div class="opt-msg trans over">
                                        <a href="#"​ class="block trans text-center" rel="nofollow">预览</a>
                                        <a href="#"​ class="block trans text-center">
                                            <i></i>详细
                                        </a>
                                    </div>
                                </div>