<div class='item wow fadeInUp fl' class="item wow fadeInUp fl">
	                        <div class="date fl">
	                            <div class="year">
	                                [field:pubdate function="MyDate('Y',@me)" /]
	                            </div>
	                            <div class="day">
	                                [field:pubdate function="MyDate('m-d',@me)" /]
	                            </div>
	                        </div>
	                        <div class="info fl">
	                            <div class="name text-over">
	                                <a href="#"​ class="trans">[field:title /]</a>
	                            </div>
	                            <div class="brief over">[field:description/]...</div>
	                        </div>
	                   </div>