<?php
$z[0]=Array("litpic","",529,544);
$z[0][4]=array();
$z[1]=Array("title","",551,591);
$z[1][4]=array();
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("arcurl","",908,924);
$z[2][4]=array();
$z[3]=Array("arcurl","",1053,1069);
$z[3][4]=array();
$z[4]=Array("title","",1612,1627);
$z[4][4]=array();
$z[5]=Array("arcurl","",1999,2015);
$z[5][4]=array();
$z[6]=Array("arcurl","",2128,2144);
$z[6][4]=array();

?>