<div class="item inline-block border-box trans">
	                                <a class="text-center block border-box trans fz0 grayscale" title="周大生" rel="nofollow">
	                                    <img src="[field:litpic/]" alt="[field:title function='html2text(@me)'/]" class="max-w100 max-h100 middle grayscale-img trans">
	                                    <span class="middle-span"></span>
	                                </a>
	                            </div>