<?php
$z[0]=Array("litpic","",473,488);
$z[0][4]=array();
$z[1]=Array("title","",495,535);
$z[1][4]=array();
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("arcurl","",858,874);
$z[2][4]=array();
$z[3]=Array("arcurl","",1004,1020);
$z[3][4]=array();
$z[4]=Array("title","",1535,1550);
$z[4][4]=array();
$z[5]=Array("arcurl","",2055,2071);
$z[5][4]=array();
$z[6]=Array("arcurl","",2186,2202);
$z[6][4]=array();

?>