<li class="case-li am-u-sm-6 am-u-md-6 am-u-lg-3">
									<div class="am-gallery-item case-img1">
										<a href="[field:arcurl /]">
											<img src="[field:litpic/]" alt="[field:title function='html2text(@me)'/]" />
										</a>
									</div>
									<div class="case-li-mengban">
										<div class=" case-word">
											<h3 class="am-gallery-title">[field:title /]</h3>
											<p>[field:pubdate function="MyDate('Y-m-d',@me)" /]</p>
											<a href="[field:arcurl /]" ><span><i class="am-icon-eye"></i>查看更多</span></a>
										</div>
									</div>
								</li>
								
								<div class="item inline-block border-box trans">
	                                <a class="text-center block border-box trans fz0 grayscale" title="周大生"
	                                rel="nofollow">
	                                    <img src="picture/1-1f92z944060-l.jpg" alt="周大生" class="max-w100 max-h100 middle grayscale-img trans">
	                                    <span class="middle-span">
	                                    </span>
	                                </a>
	                            </div>