<?php
$z[0]=Array("arcurl","",121,137);
$z[0][4]=array();
$z[1]=Array("litpic","",162,177);
$z[1][4]=array();
$z[2]=Array("title","",184,224);
$z[2][4]=array();
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("title","",379,394);
$z[3][4]=array();
$z[4]=Array("pubdate","",415,463);
$z[4][4]=array();
$z[4][4]['function']="MyDate('Y-m-d',@me)";
$z[5]=Array("arcurl","",489,505);
$z[5][4]=array();

?>