<?php
$z[0]=Array("litpic","",478,493);
$z[0][4]=array();
$z[1]=Array("title","",500,540);
$z[1][4]=array();
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("arcurl","",867,883);
$z[2][4]=array();
$z[3]=Array("arcurl","",1014,1030);
$z[3][4]=array();
$z[4]=Array("title","",1581,1596);
$z[4][4]=array();
$z[5]=Array("arcurl","",2002,2018);
$z[5][4]=array();
$z[6]=Array("arcurl","",2134,2150);
$z[6][4]=array();

?>