<li class="case-li am-u-sm-6 am-u-md-6 am-u-lg-3">
								<div class="am-gallery-item case-img1">
									<a href="[field:arcurl /]">
										<img src="[field:litpic/]" alt="[field:title function='html2text(@me)'/]" />
									</a>
								</div>
								<div class="case-li-mengban">
									<div class=" case-word">
										<h3 class="am-gallery-title">[field:title /]</h3>
										<p>[field:pubdate function="MyDate('Y-m-d',@me)" /]</p>
										<a href="[field:arcurl /]" ><span><i class="am-icon-eye"></i>查看更多</span></a>
									</div>
								</div>
							</li>
							
							<div class="item relative inline-block text-center fz0 over item-1"> 
	                            <img src=src="[field:litpic/]" alt="" class="max-w100">
	                            <a class="absolute"></a>
	                        </div>