<div class='item border-box over wow fadeInUp fl'>
                                	<div class="relative clean">
		                                <div class="cover fl relative">
		                                	<a class="trans max-w100" ondragstart="return false;" style="display: block; width: 400px; height: 250px;" ></a>
		                                   <!-- <img src="[field:litpic/]" alt="[field:title function='html2text(@me)'/]" class="trans max-w100" ondragstart="return false;">-->
		                                    <div class="img absolute text-center fz0">
		                                        <img src="[field:litpic/]" alt="[field:title function='html2text(@me)'/]" class="trans" ondragstart="return false;">
		                                    </div>
		                                </div>
		                                <div class="info fl">
		                                    <div class="clean">
		                                        <div class="logo fl text-center over fz0">
		                                            <img src="[field:litpic/]" alt="[field:title function='html2text(@me)'/]" class="middle max-w100 inline-block">
		                                            <span class="middle-span"></span>
		                                        </div>
		                                        <div class="title fl">
		                                            <div class="name">[field:title /]</div>
		                                            <div class="date">
		                                                合作时间:[field:pubdate function="MyDate('Y/m/d',@me)" /]
		                                            </div>
		                                        </div>
		                                    </div>
		                                    <div class="brief over">
		                                        [field:description/]...
		                                    </div>
		                                   <a href="[field:arcurl /]"​ ​ class="view block text-center" rel="nofollow">查看内容</a>
		                                </div>
		                            </div>
		                        </div>