<?php
$z[0]=Array("global","",368,390);
$z[0][4]=array();
$z[0][4]['name']="cfg_tel";
$z[1]=Array("global","",512,534);
$z[1][4]=array();
$z[1][4]['name']="cfg_adr";
$z[2]=Array("global","",1888,1920);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",2873,2898);
$z[3][4]=array();
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","\r\n						  <div class=\"fl\"><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></div>\r\n						       ",2945,3242);
$z[4][4]=array();
$z[4][4]['type']="top";
$z[4][4]['row']="6";
$z[4][4]['currentstyle']="<div class='on trans fl'><a href='~typelink~' ~rel~> <span>~typename~</span></a></div>";
$z[5]=Array("global","",3403,3429);
$z[5][4]=array();
$z[5][4]['name']="cfg_powerby";

?>