<?php
$z[0]=Array("global","",246,278);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",782,807);
$z[1][4]=array();
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("channel","\r\n					  <li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n					       ",852,1128);
$z[2][4]=array();
$z[2][4]['type']="top";
$z[2][4]['row']="6";
$z[2][4]['currentstyle']="<li class='on-active'><a href='~typelink~' ~rel~> <span>~typename~</span></a></li>";

?>